<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: rdfstore | ノビコード.md]]></title>
  <link href="http://fnobi.github.com/blog/categories/rdfstore/atom.xml" rel="self"/>
  <link href="http://fnobi.github.com/"/>
  <updated>2013-01-08T02:27:11+09:00</updated>
  <id>http://fnobi.github.com/</id>
  <author>
    <name><![CDATA[fnobi]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[rdfstore-jsを使うときの注意]]></title>
    <link href="http://fnobi.github.com/blog/2013/01/08/rdfstore-js/"/>
    <updated>2013-01-08T02:05:00+09:00</updated>
    <id>http://fnobi.github.com/blog/2013/01/08/rdfstore-js</id>
    <content type="html"><![CDATA[<p>　主にエラーハンドリングの処理で、イケてない部分が見つかったのでメモ。</p>

<h2>rdfstore-js</h2>

<h3>パッケージ</h3>

<ul>
<li><a href="https://npmjs.org/package/rdfstore">rdfstore</a></li>
<li><a href="https://github.com/antoniogarrote/rdfstore-js">antoniogarrote/rdfstore-js · GitHub</a></li>
</ul>


<h3>実行環境</h3>

<ul>
<li>node (v0.8.16)</li>
<li>rdfstore (v0.7.0)</li>
</ul>


<h2>store.executeについて</h2>

<p>　<code>callback(success, result)</code>の形にはなっているが、実際にはSyntaxErrorが起きた時にはcallbackしないでエラー終了してしまう。</p>

<p>　現状では、executeしている部分をまるごとtry-catchで囲むか、rdfstore側のコードを修正するしかない。</p>

<p>　SyntaxError時に直接エラーをはいているのは、L22804のthrow。(ここをthrowじゃなくてreturnにすればうまく使える?)</p>

<h2>store.loadについて</h2>

<p>　ファイルのロードに失敗した場合(たぶん厳密に言うと、指定したContentTypeでファイルが読めなかった場合)、L5294とL5295の<code>console.log</code>は、自分の環境ではいつもundefinedを返してきた。</p>

<p>　動作上は問題無いけれど、ログに邪魔なものが残るので、削っていいと思う。</p>
]]></content>
  </entry>
  
</feed>
